In [1]:
capture log close
log using "..\log\empirical_exercise6", replace
/****************************************************************************
* File name: empirical_exercise6.do
* Author(s): Sze, J.
* Date: 3/14/2019
* Description: 
* Answers to empirical exercise 6 for Labor Economics
*
* Inputs: 
* "..\input_data\Small CPS, 2018.dta"
* 
* Outputs:
* 
***************************************************************************/



---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
      name:  <unnamed>
       log:  C:\Users\jerem\Documents\Labor Economics\dofiles\..\log\empirical_exercise6.smcl
  log type:  smcl
 opened on:  18 Mar 2019, 00:16:55


This week’s exercise uses the 12,000 outgoing-rotation-group observations (1,000 observations
per month) in the Small CPS, 2018.dta extract.
The earnings weight (weight) should weight all your regression estimates, including the estimates
on grouped data. Also produce heteroskedasticity-robust standard errors.

In [2]:
use "..\input_data\Small CPS, 2018.dta",clear

(1000 Obs./Month Extract of the CPS Merged-Outgoing-Rotation-Group Files, 2018)


In [3]:
describe


Contains data from ..\input_data\Small CPS, 2018.dta
  obs:        11,000                          1000 Obs./Month Extract of the CPS Merged-Outgoing-Rotation-Group Files, 2018
 vars:            22                          17 Jan 2019 14:16
 size:       484,000                          
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
              storage   display    value
variable name   type    format     label      variable label
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
idcode          int     %9.0g               * ID Code
weight          double  %7.1f              

In [4]:
summarize


    Variable |        Obs        Mean    Std. Dev.       Min        Max
-------------+---------------------------------------------------------
      idcode |     11,000      5500.5    3175.571          1      11000
      weight |     11,000    10291.23    5648.688          0   40165.67
       month |     11,000           6    3.162421          1         11
    rotation |     11,000    6.039273    1.999705          4          8
         age |     11,000    42.17064    14.16193         15         85
-------------+---------------------------------------------------------
      female |     11,000    .4868182    .4998489          0          1
        race |     11,000    1.357091    .8956536          1          5
    hispanic |     11,000        .186    .5017873          0          2
     married |     11,000        .537    .4986518          0          1
     veteran |     10,940     .056947    .2317519          0          1
-------------+-------------------------------------------------

## A. Individual Data. 
Regress the log of weekly wages (i.e, log wages) on grade, highest
graded completed. Then regress log wages on the workweek (hours) and grade. Then
add dummy variables for occupation (i.occupation), city size (i.size), and state (i.state).
Test for the joint significance of each set of dummy variables. Describe how the estimated
effect of schooling on wages varies across these specifications, and interpret the patterns.

In [5]:
gen lnwage = log(wage)

In [6]:
regress lnwage grade [w = weight], robust

(analytic weights assumed)
(sum of wgt is 113,203,559.8744)

Linear regression                               Number of obs     =     10,984
                                                F(1, 10982)       =    1439.62
                                                Prob > F          =     0.0000
                                                R-squared         =     0.1771
                                                Root MSE          =     .73729

------------------------------------------------------------------------------
             |               Robust
      lnwage |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
       grade |   .1312027   .0034579    37.94   0.000     .1244245    .1379809
       _cons |   4.818689   .0495933    97.16   0.000     4.721478    4.915901
------------------------------------------------------------------------------


In [7]:
// A unit increase in grade leads to a 13.1% increase in wages

A unit increase in grade leads to a 13.1% increase in wages

In [8]:
test grade


 ( 1)  grade = 0

       F(  1, 10982) = 1439.62
            Prob > F =    0.0000


In [9]:
regress lnwage hours grade [w = weight], robust

(analytic weights assumed)
(sum of wgt is 113,203,559.8744)

Linear regression                               Number of obs     =     10,984
                                                F(2, 10981)       =    1851.14
                                                Prob > F          =     0.0000
                                                R-squared         =     0.4144
                                                Root MSE          =     .62201

------------------------------------------------------------------------------
             |               Robust
      lnwage |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
       hours |   .0327563   .0007956    41.17   0.000     .0311967    .0343158
       grade |   .1142533   .0029815    38.32   0.000     .1084091    .1200976
       _cons |   3.780708    .048678    77.67   0.000     3.685291    3.876126
---------------------------------

In [10]:
// A unit increase in grade leads to a 11.4% increase in wages.

A unit increase in grade leads to a 11.4% increase in wages.

In [11]:
test hours grade


 ( 1)  hours = 0
 ( 2)  grade = 0

       F(  2, 10981) = 1851.14
            Prob > F =    0.0000


In [12]:
// Hours and grade are jointly significant.

Hours and grade are jointly significant.

In [13]:
regress lnwage hours grade i.occupation [aw = weight], robust nofvlabel

(sum of wgt is 113,203,559.8744)

Linear regression                               Number of obs     =     10,984
                                                F(59, 10924)      =     134.07
                                                Prob > F          =     0.0000
                                                R-squared         =     0.5243
                                                Root MSE          =      .5621

------------------------------------------------------------------------------
             |               Robust
      lnwage |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
       hours |   .0276649   .0007664    36.10   0.000     .0261626    .0291671
       grade |   .0805218   .0033572    23.98   0.000     .0739411    .0871025
             |
  occupation |
          2  |  -.1352259   .0362323    -3.73   0.000    -.2062479    -.064204
          3  |   .0972311   .0

In [14]:
regress lnwage hours grade i.occupation i.size i.state [aw = weight], robust nofvlabel

(sum of wgt is 113,203,559.8744)

Linear regression                               Number of obs     =     10,984
                                                F(115, 10868)     =      79.25
                                                Prob > F          =     0.0000
                                                R-squared         =     0.5388
                                                Root MSE          =     .55486

------------------------------------------------------------------------------
             |               Robust
      lnwage |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
       hours |   .0278359   .0007639    36.44   0.000     .0263385    .0293332
       grade |   .0778099   .0032826    23.70   0.000     .0713754    .0842444
             |
  occupation |
          2  |  -.1385288   .0360669    -3.84   0.000    -.2092264   -.0678311
          3  |   .1073762   .0

         61  |  -.1907396   .0651013    -2.93   0.003      -.31835   -.0631291
         62  |  -.1429901   .0694481    -2.06   0.040     -.279121   -.0068592
         63  |  -.2024255   .0641439    -3.16   0.002    -.3281592   -.0766918
         64  |   -.264298   .0604546    -4.37   0.000       -.3828   -.1457961
         71  |  -.2032376    .063865    -3.18   0.001    -.3284246   -.0780507
         72  |   -.132014   .0675729    -1.95   0.051    -.2644692    .0004412
         73  |  -.1718718   .0657453    -2.61   0.009    -.3007445    -.042999
         74  |  -.1480016   .0558031    -2.65   0.008    -.2573859   -.0386174
         81  |  -.1827963   .0633713    -2.88   0.004    -.3070157    -.058577
         82  |  -.1655904    .064077    -2.58   0.010    -.2911931   -.0399878
         83  |  -.1000526   .0633233    -1.58   0.114    -.2241778    .0240726
         84  |  -.0434991   .0682622    -0.64   0.524    -.1773054    .0903073
         85  |  -.1292292   .0637377    -2.03   0.04

In [15]:
// A unit increase in grade leads to a 7.8% increase in wages.

A unit increase in grade leads to a 7.8% increase in wages.

In [16]:
testparm i.occupation hours grade


 ( 1)  hours = 0
 ( 2)  grade = 0
 ( 3)  2.occupation = 0
 ( 4)  3.occupation = 0
 ( 5)  4.occupation = 0
 ( 6)  5.occupation = 0
 ( 7)  6.occupation = 0
 ( 8)  7.occupation = 0
 ( 9)  8.occupation = 0
 (10)  9.occupation = 0
 (11)  10.occupation = 0
 (12)  11.occupation = 0
 (13)  12.occupation = 0
 (14)  13.occupation = 0
 (15)  14.occupation = 0
 (16)  15.occupation = 0
 (17)  16.occupation = 0
 (18)  17.occupation = 0
 (19)  18.occupation = 0
 (20)  19.occupation = 0
 (21)  20.occupation = 0
 (22)  21.occupation = 0
 (23)  22.occupation = 0
 (24)  23.occupation = 0
 (25)  24.occupation = 0
 (26)  25.occupation = 0
 (27)  26.occupation = 0
 (28)  27.occupation = 0
 (29)  28.occupation = 0
 (30)  29.occupation = 0
 (31)  30.occupation = 0
 (32)  31.occupation = 0
 (33)  32.occupation = 0
 (34)  33.occupation = 0
 (35)  34.occupation = 0
 (36)  35.occupation = 0
 (37)  36.occupation = 0
 (38)  37.occupation = 0
 (39)  38.occupation = 0
 (40)  39.occupation = 0
 (41)  40.occupation = 

In [17]:
// The occupation dummies, hours and grade are jointly significant.

The occupation dummies, hours and grade are jointly significant.

In [18]:
testparm i.state hours grade


 ( 1)  hours = 0
 ( 2)  grade = 0
 ( 3)  12.state = 0
 ( 4)  13.state = 0
 ( 5)  14.state = 0
 ( 6)  15.state = 0
 ( 7)  16.state = 0
 ( 8)  21.state = 0
 ( 9)  22.state = 0
 (10)  23.state = 0
 (11)  31.state = 0
 (12)  32.state = 0
 (13)  33.state = 0
 (14)  34.state = 0
 (15)  35.state = 0
 (16)  41.state = 0
 (17)  42.state = 0
 (18)  43.state = 0
 (19)  44.state = 0
 (20)  45.state = 0
 (21)  46.state = 0
 (22)  47.state = 0
 (23)  51.state = 0
 (24)  52.state = 0
 (25)  53.state = 0
 (26)  54.state = 0
 (27)  55.state = 0
 (28)  56.state = 0
 (29)  57.state = 0
 (30)  58.state = 0
 (31)  59.state = 0
 (32)  61.state = 0
 (33)  62.state = 0
 (34)  63.state = 0
 (35)  64.state = 0
 (36)  71.state = 0
 (37)  72.state = 0
 (38)  73.state = 0
 (39)  74.state = 0
 (40)  81.state = 0
 (41)  82.state = 0
 (42)  83.state = 0
 (43)  84.state = 0
 (44)  85.state = 0
 (45)  86.state = 0
 (46)  87.state = 0
 (47)  88.state = 0
 (48)  91.state = 0
 (49)  92.state = 0
 (50)  93.state = 0
 (51)

In [19]:
// The state dummies, hours and grade are jointly significant.

The state dummies, hours and grade are jointly significant.

## B. Occupation Averages. 
Weighting the averages by the earnings weight (weight), collapse
the data by occupation. (Carry along the sum of the weights by occupation, too.) On
the occupation averages, regress log wages on the workweek and schooling. Compare
your estimate of the effect of schooling on wages across occupations with those from the
individual data.

In [20]:
gen weight_occupation = 1

In [21]:
collapse (mean) lnwage hours grade female ///
(sum) weight_occupation ///
[w = weight], by(occupation)

(analytic weights assumed)


In [22]:
regress lnwage hours grade [w = weight_occupation], robust

(analytic weights assumed)
(sum of wgt is 10,984)

Linear regression                               Number of obs     =         58
                                                F(2, 55)          =     151.38
                                                Prob > F          =     0.0000
                                                R-squared         =     0.8813
                                                Root MSE          =     .16182

------------------------------------------------------------------------------
             |               Robust
      lnwage |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
       hours |   .0814257    .007355    11.07   0.000      .066686    .0961655
       grade |   .1347429   .0205678     6.55   0.000     .0935242    .1759616
       _cons |    1.59674    .285429     5.59   0.000     1.024727    2.168752
-------------------------------------------

In [23]:
/* A one unit increase in grade leads to a 13.5% increase in wages in the above model. 
In the individual model, a one unit increase in grade leadds to a 7.8% increase in wages.
*/

A one unit increase in grade leads to a 13.5% increase in wages in the above model. In the individual model, a one unit increase in grade leadds to a 7.8% increase in wages. The magnitude in the occupation average model is almost twice the size of the individual model. It seems that certain occupations have higher average levels of schooling and also pay higher wages, and certain occupations have lower average levels of schooling and pay lower wages. In this occupation average model, the effect of schooling is stronger.

## C. State Averages. 
Weighting the averages by the earnings weight (weight), collapse the
data by state. On the state averages, regress log wages on the workweek and schooling,
and compare your estimates with those from the individual data.

In [24]:
use "..\input_data\Small CPS, 2018.dta",clear

(1000 Obs./Month Extract of the CPS Merged-Outgoing-Rotation-Group Files, 2018)


In [25]:
gen weight_state = 1
gen lnwage = log(wage)

In [26]:
collapse (mean) lnwage hours grade female ///
(sum) weight_state ///
[pw = weight], by(state)

In [27]:
regress lnwage hours grade [aw = weight_state], robust

(sum of wgt is 113,203,559.8744)

Linear regression                               Number of obs     =         51
                                                F(2, 48)          =      24.99
                                                Prob > F          =     0.0000
                                                R-squared         =     0.5313
                                                Root MSE          =     .08495

------------------------------------------------------------------------------
             |               Robust
      lnwage |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
       hours |   .0044484   .0247674     0.18   0.858    -.0453497    .0542466
       grade |   .2411074   .0367236     6.57   0.000     .1672696    .3149451
       _cons |   3.102904   1.270786     2.44   0.018     .5478181    5.657991
------------------------------------------------------------

In [28]:
/* In the above model, we find that a unit increase in grades leads to a 24.81% increase in wages. 
This is larger than the 13.5% increase found when we regress occupation wages against grades and hours.
*/

In the above model, we find that a unit increase in grades leads to a 24.8% increase in wages. This is larger than the 13.5% increase found when we regress occupation wages against grades and hours. As this is a "coarser" model of state averages, the effect of schooling on wages is magnified larger.

In [29]:
log close

      name:  <unnamed>
       log:  C:\Users\jerem\Documents\Labor Economics\dofiles\..\log\empirical_exercise6.smcl
  log type:  smcl
 closed on:  18 Mar 2019, 00:17:08
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
